/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: VADC BG Example for
*              ModusToolbox. This example shows how to convert a single
*              channel using the background source. The background source
*              is continuously requesting the conversion. The result is
*              stored in the result register and read out in the while
*              loop of main.c. The result values will be printed in UART
*              Terminal. The LED glows when the ADC result is higher
*              than 2000 counts.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2022, Infineon Technologies AG
* All rights reserved.
*
* Boost Software License - Version 1.0 - August 17th, 2003
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT

* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/

#include <stdio.h>
#include "cybsp.h"
#include "cy_utils.h"
#include "cy_retarget_io.h"

/*******************************************************************************
* Macros
*******************************************************************************/

/* Define macros for XMC1x Boot kit */
#if (UC_FAMILY == XMC1)
#define RES_REG_NUMBER                      (10)    /* Result register number */
    #if (UC_SERIES == XMC13) || (UC_SERIES == XMC14)
    #define CHANNEL_NUMBER                  (7U)    /* Channel number */
    #else
    #define CHANNEL_NUMBER                  (4U)    /* Channel number */
    #endif
#endif

/* Define macros for XMC4x kit */
#if (UC_FAMILY == XMC4)
#define RES_REG_NUMBER                      (4)     /* Result register number */
    #if (UC_SERIES==XMC42) || (UC_SERIES==XMC43) || (UC_SERIES==XMC44)
    #define CHANNEL_NUMBER                  (0U)    /* Channel number */
    #elif (UC_SERIES == XMC48) || (UC_SERIES == XMC47)
    #define CHANNEL_NUMBER                  (5U)    /* Channel number */
    #else
    #define CHANNEL_NUMBER                  (6U)    /* Channel number */
    #endif
#endif

/*******************************************************************************
* Defines
*******************************************************************************/

/* Define macro to enable/disable printing of debug messages */
#define ENABLE_XMC_DEBUG_PRINT              (0)

/* Define macro to set the loop count before printing debug messages */
#if ENABLE_XMC_DEBUG_PRINT
#define DEBUG_LOOP_COUNT_MAX                (1U)
#endif

/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function.
* It sets up a VADC using background scan source.
* The background source is continuously requesting the conversion.
* The result is stored in the result register and read out in the while loop.
* The result values will be printed in UART Terminal.
* On board LED glows high when ADC counts are more than 2000.
*
* Parameters:
*  none
*
* Return:
*  int
*
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;

    /* ADC result variable */
    XMC_VADC_RESULT_SIZE_t adc_result = 0;

    #if ENABLE_XMC_DEBUG_PRINT
    /* Initialize the current loop counters to zero */
    static uint32_t debug_loop_count_over_limit  = 0;
    static uint32_t debug_loop_count_below_limit = 0;
    #endif

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Initialize retarget-io to use the debug UART port */
    cy_retarget_io_init(CYBSP_DEBUG_UART_HW);
    printf("ADC Conversion starts \r\n");

    /* Add a channel to the background source */
    XMC_VADC_GLOBAL_BackgroundAddChannelToSequence(VADC, VADC_GROUP_NUM, CHANNEL_NUMBER);

    /* Enables Auto scan feature for continuous conversion */
    XMC_VADC_GLOBAL_BackgroundEnableContinuousMode(VADC);

    /* Generate a load event to start background request source continuous conversion */
    XMC_VADC_GLOBAL_BackgroundTriggerConversion(VADC);

    while (1U)
    {
        #if (UC_SERIES == XMC11)
        /* Retrieve result from result register */
        adc_result = XMC_VADC_GLOBAL_GetResult(VADC);
        #else
        adc_result = XMC_VADC_GROUP_GetResult(VADC_GROUP_HW, RES_REG_NUMBER);
        #endif

        /* Prints the result in UART Terminal */
        printf("ADC Result value is %x \r\n", adc_result);

        /* Compare the result counts */
        if (adc_result >= 2000)
        {
            #if ENABLE_XMC_DEBUG_PRINT
            debug_loop_count_over_limit++;
            if (debug_loop_count_over_limit == DEBUG_LOOP_COUNT_MAX)
            {
                /* Print message after the loop has run DEBUG_LOOP_COUNT_MAX times */
                printf("ADC result greater than 2000\r\n");
            }
            #endif
            #if (UC_FAMILY == XMC1)
                #if (UC_SERIES == XMC11)
                XMC_GPIO_SetOutputLow(CYBSP_USER_LED3_PORT, CYBSP_USER_LED3_PIN);
                #else
                XMC_GPIO_SetOutputLow(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
                #endif
            #endif

            #if (UC_FAMILY == XMC4)
            XMC_GPIO_SetOutputHigh(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
            #endif
        }
        else
        {
            #if ENABLE_XMC_DEBUG_PRINT
            debug_loop_count_below_limit++;
            if (debug_loop_count_below_limit == DEBUG_LOOP_COUNT_MAX)
            {
                /* Print message after the loop has run DEBUG_LOOP_COUNT_MAX times */
                printf("ADC result less than 2000\r\n");
            }
            #endif
            #if (UC_FAMILY == XMC1)
                #if (UC_SERIES == XMC11)
                XMC_GPIO_SetOutputHigh(CYBSP_USER_LED3_PORT, CYBSP_USER_LED3_PIN);
                #else
                XMC_GPIO_SetOutputHigh(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
                #endif
            #endif

            #if (UC_FAMILY == XMC4)
            XMC_GPIO_SetOutputLow(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
            #endif
        }
    }
    return 1;
}

/* [] END OF FILE */
