/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: VADC BG Example for
*              ModusToolbox. This example shows how to convert a single
*              channel using the background source. The background source
*              is continuously requesting the conversion. The result is
*              stored in the result register and read out in the while
*              loop of main.c. The result values will be printed in UART
*              Terminal. The LED glows when the ADC result is higher
*              than 2000 counts.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2020, Infineon Technologies AG
* All rights reserved.
*
* Boost Software License - Version 1.0 - August 17th, 2003
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT

* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/
#include "cybsp.h"
#include "cy_utils.h"
#include <xmc_vadc.h>
#include <stdio.h>
#include "retarget_io.h"

/*******************************************************************************
* Macros
*******************************************************************************/
/* Define macros for XMC14x Boot kit */
#ifdef TARGET_KIT_XMC14_BOOT_001
#define RES_REG_NUMBER                 (10)          /* Result register number*/
#define CHANNEL_NUMBER                 (7U)          /* Channel number */
#define GROUP_NUMBER                   (1U)          /* Group number */
#define VADC_GROUP_PTR                 (VADC_G1)     /* VADC group G1 */
#endif

/* Define macros for XMC47x Relax kit */
#ifdef TARGET_KIT_XMC47_RELAX_V1
#define RES_REG_NUMBER                 (4)           /* Result register number*/
#define CHANNEL_NUMBER                 (5U)          /* Channel number */
#define GROUP_NUMBER                   (3U)          /* Group number */
#define VADC_GROUP_PTR                 (VADC_G3)     /* VADC group G3 */
#endif

/*******************************************************************************
* Data Structures
*******************************************************************************/
/* Initialization data of a VADC Global */
XMC_VADC_GLOBAL_CONFIG_t g_global_config =
{
    .clock_config =
    {
    .analog_clock_divider    = 3,  /* Clock for the converter */
    },
};

/* VADC group data configuration. No configuration needed, standard values
 * are used.
 */
const XMC_VADC_GROUP_CONFIG_t g_group_handle = { };

/* Data configuration for background source */
const XMC_VADC_BACKGROUND_CONFIG_t g_bgn_handle = { };

/* Initialization data of a VADC Channel */
XMC_VADC_CHANNEL_CONFIG_t  g_channel_config =
{
    .alias_channel     = (int8_t)  XMC_VADC_CHANNEL_ALIAS_DISABLED, /* ALIAS is Disabled */
    .result_reg_number = RES_REG_NUMBER, /* Result Register */
};

/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function.
* It sets up a VADC using background scan source.
* The background source is continuously requesting the conversion.
* The result is stored in the result register and read out in the while loop.
* The result values will be printed in UART Terminal.
* On board LED glows high when ADC counts are more than 2000.
*
* Parameters:
*  none
*
* Return:
*  int
*
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;

    /* ADC result variable */
    XMC_VADC_RESULT_SIZE_t adc_result = 0;

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Initialize retarget-io to use the debug UART port */
    retarget_io_init();
    printf("ADC Conversion starts \r\n");

    /* Initialize an instance of Global hardware */
    XMC_VADC_GLOBAL_Init(VADC, &g_global_config);

    /* Initialize Group */
    XMC_VADC_GROUP_Init(VADC_GROUP_PTR, &g_group_handle);

    /* Set VADC group to normal operation mode (VADC kernel) */
    XMC_VADC_GROUP_SetPowerMode(VADC_GROUP_PTR, XMC_VADC_GROUP_POWERMODE_NORMAL);

    /* Calibrate the VADC. Make sure you do this after all used VADC groups
    * are set to normal operation mode */
    XMC_VADC_GLOBAL_StartupCalibration(VADC);

    /* Initialize the background source hardware. The gating mode is set to
    * ignore to pass external triggers unconditionally */
    XMC_VADC_GLOBAL_BackgroundInit(VADC, &g_bgn_handle);

    /* Initialize the channel unit */
    XMC_VADC_GROUP_ChannelInit(VADC_GROUP_PTR, CHANNEL_NUMBER, &g_channel_config );

    /* Add a channel to the background source */
    XMC_VADC_GLOBAL_BackgroundAddChannelToSequence(VADC, GROUP_NUMBER, CHANNEL_NUMBER);

    /* Enables Auto scan feature for continuous conversion */
    XMC_VADC_GLOBAL_BackgroundEnableContinuousMode(VADC);

    /* Generate a load event to start background request source continuous conversion */
    XMC_VADC_GLOBAL_BackgroundTriggerConversion(VADC);

    while (1U)
    {
        /* Retrieve result from result register */
        adc_result = XMC_VADC_GROUP_GetResult(VADC_GROUP_PTR,RES_REG_NUMBER);

        /* Prints the result in UART Terminal */
        printf("ADC Result value is %x \r\n", adc_result);

        /* Compare the result counts */
        if(adc_result >= 2000)
        {
            #ifdef TARGET_KIT_XMC14_BOOT_001
            XMC_GPIO_SetOutputLow(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
            #endif

            #ifdef TARGET_KIT_XMC47_RELAX_V1
            XMC_GPIO_SetOutputHigh(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
            #endif
        }
        else
        {
            #ifdef TARGET_KIT_XMC14_BOOT_001
            XMC_GPIO_SetOutputHigh(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
            #endif

            #ifdef TARGET_KIT_XMC47_RELAX_V1
            XMC_GPIO_SetOutputLow(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
            #endif
        }
    }
    return 1;
}

/* [] END OF FILE */